---
title: "Geneset_Enrichment_Analysis"
output: html_document
date: "2024-07-08"
---

### Install and load the neccessary libraries and packages
```{r}
BiocManager::install("ReactomePA")
if (!requireNamespace("msigdbr", quietly = TRUE)) {
  install.packages("msigdbr")
}

# Load the required packages
library(clusterProfiler)
library(org.Mm.eg.db)
library(enrichplot)
library(ReactomePA)
library(msigdbr)
library(dplyr)
```

### Load the annotated data
```{r}
# Load your annotated data
annotated_data <- read.csv("Silencing/GPS2/results/annotation/sictl_vs_sigps2_annotated.txt", sep = '\t')  # Replace with your file path
```

### MSIGDB Analysis
```{r}
# Assuming your data is in a dataframe called 'results'
# Extract the gene symbols
gene_list <- unique(annotated_data$SYMBOL)

# Remove any NA values
gene_list <- gene_list[!is.na(gene_list)]

# Get the desired MSigDB gene sets for mouse
msigdb_hallmark <- msigdbr(species = "Mus musculus", category = "H")

ora_result <- enricher(
  gene = gene_list,
  TERM2GENE = msigdb_hallmark %>% dplyr::select(gs_name, gene_symbol),
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH"
)

#Choose the appropriate directory to save the file
output_dir <- "/projectnb/perissilab/Jawahar/GPS2_ChIPseq_Perissi-Lab/Silencing/GPS2/results/GSEA"

# Create the directory if it does not exist
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)}

msigdb_result <- ora_result@result

output_file <- file.path(output_dir, paste0(basename("sictl_vs_sigps2"), "_msigdb.txt"))
write.table(as.data.frame(msigdb_result), file=output_file, sep="\t", quote=FALSE, row.names=FALSE)
```

### Visualize the results
```{r}
# Plot the top enriched pathways
dotplot(ora_result, showCategory = 10, title = "Enriched Pathways", )

# Generate a bar plot of enriched terms
barplot(ora_result, showCategory = 10)
```

### Split regions -- Optional
```{r}
# Split data into promoters and other regions
promoter_data <- subset(annotated_data, annotation == "Promoter (<=1kb)" | annotation == "Promoter (1-2kb)" | annotation == "Promoter (2-3kb)")

non_promoter_data <- subset(annotated_data, !(annotation == "Promoter (<=1kb)" | annotation == "Promoter (1-2kb)" | annotation == "Promoter (2-3kb)"))


# Gene names for promoters
promoter_genes <- unique(promoter_data$SYMBOL)
non_promoter_genes <- unique(non_promoter_data$SYMBOL)
promoters_entrez <- unique(promoter_data$geneId)
non_promoters_entrez <- unique(non_promoter_data$geneId)
```

### GO Enrichment
```{r}
ego_promoter_results <- enrichGO(
  gene = non_promoters_entrez,
  OrgDb = org.Mm.eg.db,
  keyType = "SYMBOL",  # Adjust if your gene identifiers are different
  ont = "BP",
  pvalueCutoff = 0.05,
  qvalueCutoff = 0.2
)
```

### KEGG Enrichment
```{r}
# KEGG Pathway Enrichment
kegg_enrichment <- enrichKEGG(gene = promoters_entrez,
                              organism = 'mmu',  # 'hsa' for Homo sapiens
                              pvalueCutoff = 0.05,
                              pAdjustMethod = "BH")
```

### Reactome Pathway Analysis
```{r}
# Reactome Pathway Enrichment

Reactome_enrichment <- enrichPathway(gene=promoters_entrez, organism = 'mouse', pvalueCutoff = 0.05, pAdjustMethod = "BH", readable=TRUE)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
